name: CI (against releases)

on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch:
  workflow_call:

jobs:
  test_0_1_0_installing_from_github:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.1.0.post0
    with:
      ref: v0.1.0

  test_0_1_0_installing_from_pypi:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.1.0.post0
    with:
      ref: v0.1.0
      index: PyPI
      index_version: 0.1.0

  test_0_2_0_installing_from_github:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.2.0.post0
    with:
      ref: v0.2.0

  test_0_2_0_installing_from_pypi:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.2.0.post0
    with:
      ref: v0.2.0
      index: PyPI
      index_version: 0.2.0

  test_0_2_1_installing_from_github:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.2.1.post0
    with:
      ref: v0.2.1

  test_0_2_1_installing_from_pypi:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.2.1.post0
    with:
      ref: v0.2.1
      index: PyPI
      index_version: 0.2.1

  test_0_3_0_installing_from_github:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.3.0
    with:
      ref: v0.3.0

  test_0_3_0_installing_from_pypi:
    uses: nbvalx/nbvalx/.github/workflows/ci.yml@v0.3.0
    with:
      ref: v0.3.0
      index: PyPI
      index_version: 0.3.0

  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'nbvalx/nbvalx' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: ci_against_releases.yml
          days-elapsed: 50
